In [1]:
import numpy as np

In [4]:
arr1=np.array([[1,2,3,4]])
arr2=np.array([[2,2,2,2]])
arr3= np.concatenate((arr1,arr2))
arr3

array([[1, 2, 3, 4],
       [2, 2, 2, 2]])

In [5]:
arr4=np.concat((arr1,arr2),axis=1)
arr4

array([[1, 2, 3, 4, 2, 2, 2, 2]])

In [6]:
arr5=np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
arr6=np.array([[1,1,1,1,1,1],[4,4,4,4,4,4]])

In [7]:
np.concatenate([arr5,arr6],axis=0)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  1,  1,  1,  1,  1],
       [ 4,  4,  4,  4,  4,  4]])

In [8]:
np.vstack([arr5,arr6])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [ 1,  1,  1,  1,  1,  1],
       [ 4,  4,  4,  4,  4,  4]])

In [9]:
np.hstack([arr5,arr6])

array([[ 1,  2,  3,  4,  5,  6,  1,  1,  1,  1,  1,  1],
       [ 7,  8,  9, 10, 11, 12,  4,  4,  4,  4,  4,  4]])

In [3]:
import numpy as np
arr7=np.array([[1,2,3],[4,5,6]])
arr8=np.array([[2,2,2]])

In [4]:
np.vstack([arr7,arr8])

array([[1, 2, 3],
       [4, 5, 6],
       [2, 2, 2]])

In [5]:
arr9=np.array([[10],[10]])
np.hstack([arr7,arr9])

array([[ 1,  2,  3, 10],
       [ 4,  5,  6, 10]])