In [5]:
import numpy as np

In [6]:
array1=np.linspace(-np.pi,np.pi,10)
array1

array([-3.14159265, -2.44346095, -1.74532925, -1.04719755, -0.34906585,
        0.34906585,  1.04719755,  1.74532925,  2.44346095,  3.14159265])

In [7]:
sin_value=np.sin(array1)

In [8]:
sin_value

array([-1.22464680e-16, -6.42787610e-01, -9.84807753e-01, -8.66025404e-01,
       -3.42020143e-01,  3.42020143e-01,  8.66025404e-01,  9.84807753e-01,
        6.42787610e-01,  1.22464680e-16])

In [9]:
sin_value=np.round(sin_value,3)

In [10]:
sin_value

array([-0.   , -0.643, -0.985, -0.866, -0.342,  0.342,  0.866,  0.985,
        0.643,  0.   ])

Using meanin numpy array

In [11]:
array1=np.array([1,5,7,8])
mean=np.mean(array1)

In [12]:
print(mean)

5.25


In [13]:
array2=np.array([[6,7,8,10],
                 [8,3,5,12],
                 [10,23,4,6],
                 [10,12,16,18]])

In [14]:
array2

array([[ 6,  7,  8, 10],
       [ 8,  3,  5, 12],
       [10, 23,  4,  6],
       [10, 12, 16, 18]])

In [15]:
mean=np.mean(array2)

In [16]:
print(mean)

9.875


In [17]:
mean_1=np.mean(array2,axis=0)
mean_1

array([ 8.5 , 11.25,  8.25, 11.5 ])

In [18]:
mean_2=np.mean(array2,axis=0)
mean_2

array([ 8.5 , 11.25,  8.25, 11.5 ])

# Random number in numpy

In [19]:
# rand
# randint

rand_array=np.random.rand(4,4)
rand_array

array([[0.78347036, 0.99486707, 0.75509691, 0.80315391],
       [0.25391763, 0.33844762, 0.94744321, 0.30045739],
       [0.28094385, 0.45015207, 0.95187322, 0.29405361],
       [0.97265398, 0.82586461, 0.56572184, 0.52603458]])

In [20]:
randint_array=np.random.randint(10,20,size=(4,5))

In [21]:
randint_array

array([[12, 17, 15, 12, 17],
       [15, 14, 15, 13, 19],
       [15, 14, 11, 18, 19],
       [17, 12, 17, 17, 17]], dtype=int32)

Split() method in numpy array

In [22]:
import numpy as np
array1=np.random.randint(10,51,size=(5,6))
array1

array([[20, 26, 38, 36, 42, 21],
       [38, 26, 19, 18, 31, 48],
       [31, 22, 28, 50, 21, 19],
       [16, 13, 44, 29, 43, 17],
       [45, 23, 35, 44, 49, 16]], dtype=int32)

In [23]:
array_first,array_second=np.split(array1,[3],axis=0)

In [24]:
array_first

array([[20, 26, 38, 36, 42, 21],
       [38, 26, 19, 18, 31, 48],
       [31, 22, 28, 50, 21, 19]], dtype=int32)

In [25]:
array_second

array([[16, 13, 44, 29, 43, 17],
       [45, 23, 35, 44, 49, 16]], dtype=int32)

In [26]:
array_columnpart1,array_columnpart2=np.split(array1,[3],axis=1)

In [27]:
array_columnpart1

array([[20, 26, 38],
       [38, 26, 19],
       [31, 22, 28],
       [16, 13, 44],
       [45, 23, 35]], dtype=int32)

In [28]:
array_columnpart2

array([[36, 42, 21],
       [18, 31, 48],
       [50, 21, 19],
       [29, 43, 17],
       [44, 49, 16]], dtype=int32)

In [29]:
array_columnpart1.shape

(5, 3)

In [30]:
array_columnpart2.shape

(5, 3)

Loading the data from txt

In [31]:
iris_array=np.genfromtxt (r"C:\Users\Samriddha Dhakal\OneDrive\Desktop\AI_ml\Num_py\iris.txt",delimiter=',',dtype=str)

In [32]:
iris_array

array([['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa'],
       ['4.6', '3.4', '1.4', '0.3', 'Iris-setosa'],
       ['5.0', '3.4', '1.5', '0.2', 'Iris-setosa'],
       ['4.4', '2.9', '1.4', '0.2', 'Iris-setosa'],
       ['4.9', '3.1', '1.5', '0.1', 'Iris-setosa'],
       ['5.4', '3.7', '1.5', '0.2', 'Iris-setosa'],
       ['4.8', '3.4', '1.6', '0.2', 'Iris-setosa'],
       ['4.8', '3.0', '1.4', '0.1', 'Iris-setosa'],
       ['4.3', '3.0', '1.1', '0.1', 'Iris-setosa'],
       ['5.8', '4.0', '1.2', '0.2', 'Iris-setosa'],
       ['5.7', '4.4', '1.5', '0.4', 'Iris-setosa'],
       ['5.4', '3.9', '1.3', '0.4', 'Iris-setosa'],
       ['5.1', '3.5', '1.4', '0.3', 'Iris-setosa'],
       ['5.7', '3.8', '1.7', '0.3', 'Iris-setosa'],
       ['5.1

In [33]:
features, labels=np.split(iris_array,[4],axis=1)

In [34]:
features.shape

(150, 4)

In [35]:
labels.shape

(150, 1)

In [36]:
features[:5]

array([['5.1', '3.5', '1.4', '0.2'],
       ['4.9', '3.0', '1.4', '0.2'],
       ['4.7', '3.2', '1.3', '0.2'],
       ['4.6', '3.1', '1.5', '0.2'],
       ['5.0', '3.6', '1.4', '0.2']], dtype='<U15')

In [37]:
labels[:5]

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa']], dtype='<U15')

In [38]:
features=features.astype(float)

In [39]:
features[:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [42]:

mean_feature=np.mean(features,axis=0)

In [41]:
mean_feature

array([5.84333333, 3.054     , 3.75866667, 1.19866667])

Broadcastiong in numpy array