In [ ]:
import numpy as np

Creating numpy array


In [ ]:
arr1= np.array({3,5,6,8,10})
print(arr1)
print(type(arr1))

{3, 5, 6, 8, 10}
<class 'numpy.ndarray'>


Creating two dimensional array

In [ ]:
array_2d=np.array([[3,4,5],[6,7,8],[1,2,3]])
array_2d

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 3]])

In [ ]:
array_2d=np.array([[3,4,5],[6,7,8],[1,2,3]])
print(array_2d)
print(type(array_2d))


[[3 4 5]
 [6 7 8]
 [1 2 3]]
<class 'numpy.ndarray'>


To check the dimension of array

In [ ]:
arr1.ndim

0

To create 3d

In [ ]:
array_3d=np.array([[[1,2,3],[4,5,6],[6,7,8],[8,9,10]]])
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 6,  7,  8],
        [ 8,  9, 10]]])

Multiple arrays

In [ ]:
arr_100=np.arange(1,101)
arr_100

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

line space


In [ ]:
arr2=np.linspace(1,5,10)
print(arr2)

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]


Creating 1 and 0 identity matrix

In [ ]:
arr_zero=np.zeros(8)
arr_zero

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
arr_zero=np.zeros((8,8))
arr_zero

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
arr_zero=np.zeros((8,8), dtype=int)
arr_zero

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
arr_identity=np.eye(8)

In [ ]:
arr_identity

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
arr_identity=np.eye(8,dtype=int)

In [ ]:
arr_identity

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 1]])

To check the shape of nd array

In [ ]:
array_3d.shape

(1, 4, 3)

In [ ]:
ar1=np.array([2,4,5])
ar2=np.array([2,6,4])
print(ar1+ar2)

[ 4 10  9]


Create 2d array and multiply

In [ ]:
import numpy as np

arry2d1 = np.array([[4,5,6],[6,7,8],[7,8,9]])
arry2d2 = np.array([[1,2,3],[3,4,5],[6,7,8]])

print(arry2d1 * arry2d2)



[[ 4 10 18]
 [18 28 40]
 [42 56 72]]


In [ ]:
ary2d1=np.array([[4,5,6],[6,7,8],[7,8,9]])
ary2d2=np.array([[1,2,3],[3,4,5],[6,7,8]])
print(ary2d1@ary2d2)

[[ 55  70  85]
 [ 75  96 117]
 [ 85 109 133]]


Creating multidimensional array

In [3]:
import numpy as np
array1=np.array([2,3,4,5], ndmin=5)
array1

array([[[[[2, 3, 4, 5]]]]])

In [4]:
array1.shape

(1, 1, 1, 1, 4)

Operation in array

In [5]:
array1=np.array([4,8,9,12])
print(array1+10)
#Vectorization in numpy array

[14 18 19 22]


Indexing in numpy array

In [6]:
print(array1[1])

8


In [11]:
array2=np.array([[1,2,3,4],[6,7,3,4],[10,18,19,14]])
array2

array([[ 1,  2,  3,  4],
       [ 6,  7,  3,  4],
       [10, 18, 19, 14]])

In [13]:
print(array2[1][1])
print(array2[1,1])

7
7


Slicing in numpy array

In [14]:
array2

array([[ 1,  2,  3,  4],
       [ 6,  7,  3,  4],
       [10, 18, 19, 14]])

In [15]:
#array2[start_row:end_row, start_column:end_column]
array2[0:2,0:4]

array([[1, 2, 3, 4],
       [6, 7, 3, 4]])

In [16]:
array2[0:2, :]

array([[1, 2, 3, 4],
       [6, 7, 3, 4]])

In [21]:
array2[1:3,1:3]

array([[ 7,  3],
       [18, 19]])

Reshaping an array

In [22]:
array2d=np.array([[1,2,3,4],
                  [5,6,7,8],
                  [9,10,11,12]])

In [23]:
array2d.shape

(3, 4)

In [26]:
array2d_reshape=array2d.reshape(1,12)
array2d_reshape

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [27]:
array2d_reshape.shape

(1, 12)

In [28]:
array2d_1d=array2d.reshape(12)
array2d_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [29]:
array2d_1d.reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

To store 1 to 100 2dimensional array shape (5,20)

In [6]:
import numpy as np
array1d=np.arange(1,101)
array1d

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
array2d=array1d.reshape(5,20)

In [8]:
array2d

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30,  31,  32,  33,
         34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,
         74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]])

In [9]:
array2d.shape

(5, 20)